.TH FYRE 1 "Sep  4, 2004"
.SH NAME
fyre \- Interactively renders Peter de Jong maps
.SH SYNOPSIS
.B fyre
[ OPTIONS ]
.SH DESCRIPTION
.B fyre
Fyre provides a rendering of the Peter de Jong map, with an interactive
GTK+ frontend and a command line interface for easy and efficient rendering
of high-resolution, high quality images.
.SH OPTIONS
Please run
.B fyre -h
to get a complete list of options.
.SH AUTHORS
The original program was written by David Trowbridge and Micah Dowty. This
manual page was provided by Christoph Haas <haas@debian.org> for the
Debian GNU/Linux system.

